package com.dj.boot.webservice.webclient;

import com.dj.boot.webservice.webserver.impl.WebServiceGoodsDeliveryServiceImpl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.4.1
 * 2021-06-10T15:12:11.397+08:00
 * Generated source version: 3.4.1
 *
 */
@WebServiceClient(name = "WebServiceGoodsDeliveryServiceImplService",
                  wsdlLocation = "http://127.0.0.1:8088/WS_Server/Webservice/WebServiceGoodsDeliveryService?wsdl",
                  targetNamespace = "http://impl.webserver.webservice.boot.dj.com/")
public class WebServiceGoodsDeliveryServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.webserver.webservice.boot.dj.com/", "WebServiceGoodsDeliveryServiceImplService");
    public final static QName WebServiceGoodsDeliveryServiceImplPort = new QName("http://impl.webserver.webservice.boot.dj.com/", "WebServiceGoodsDeliveryServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://127.0.0.1:8088/WS_Server/Webservice/WebServiceGoodsDeliveryService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(WebServiceGoodsDeliveryServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://127.0.0.1:8088/WS_Server/Webservice/WebServiceGoodsDeliveryService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public WebServiceGoodsDeliveryServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public WebServiceGoodsDeliveryServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WebServiceGoodsDeliveryServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public WebServiceGoodsDeliveryServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public WebServiceGoodsDeliveryServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public WebServiceGoodsDeliveryServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns WebServiceGoodsDeliveryServiceImpl
     */
    @WebEndpoint(name = "WebServiceGoodsDeliveryServiceImplPort")
    public com.dj.boot.webservice.webserver.impl.WebServiceGoodsDeliveryServiceImpl getWebServiceGoodsDeliveryServiceImplPort() {
        return super.getPort(WebServiceGoodsDeliveryServiceImplPort, com.dj.boot.webservice.webserver.impl.WebServiceGoodsDeliveryServiceImpl.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WebServiceGoodsDeliveryServiceImpl
     */
    @WebEndpoint(name = "WebServiceGoodsDeliveryServiceImplPort")
    public com.dj.boot.webservice.webserver.impl.WebServiceGoodsDeliveryServiceImpl getWebServiceGoodsDeliveryServiceImplPort(WebServiceFeature... features) {
        return super.getPort(WebServiceGoodsDeliveryServiceImplPort, WebServiceGoodsDeliveryServiceImpl.class, features);
    }

}
