package com.dj.boot.webservice.webclient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.4.1
 * 2021-06-10T15:12:11.348+08:00
 * Generated source version: 3.4.1
 *
 */
@WebService(targetNamespace = "http://impl.webserver.webservice.boot.dj.com/", name = "WebServiceGoodsDeliveryServiceImpl")
@XmlSeeAlso({ObjectFactory.class})
public interface WebServiceGoodsDeliveryServiceImpl {

    @WebMethod
    @Action(input = "http://impl.webserver.webservice.boot.dj.com/WebServiceGoodsDeliveryServiceImpl/transportGrantUserPermissionRequest", output = "http://impl.webserver.webservice.boot.dj.com/WebServiceGoodsDeliveryServiceImpl/transportGrantUserPermissionResponse")
    @RequestWrapper(localName = "transportGrantUserPermission", targetNamespace = "http://impl.webserver.webservice.boot.dj.com/", className = "com.dj.boot.webservice.webserver.impl.TransportGrantUserPermission")
    @ResponseWrapper(localName = "transportGrantUserPermissionResponse", targetNamespace = "http://impl.webserver.webservice.boot.dj.com/", className = "com.dj.boot.webservice.webserver.impl.TransportGrantUserPermissionResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String transportGrantUserPermission(

            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0
    );
}
